"use client";

import type { GeneratedDocument } from "@/types/schema";
import { normalizeMermaidMarkdown } from "@/lib/mermaid-markdown";
import { renderMermaidSvg } from "@/lib/mermaid-client";

/**
 * Download a document as a Markdown file.
 */
export function downloadAsMarkdown(document: GeneratedDocument): void {
  const blob = new Blob([document.content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const anchor = window.document.createElement("a");
  anchor.href = url;
  anchor.download = document.filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

/**
 * Download all documents as individual Markdown files.
 */
export function downloadAllMarkdown(documents: GeneratedDocument[]): void {
  documents.forEach((doc, index) => {
    setTimeout(() => downloadAsMarkdown(doc), index * 300);
  });
}

/**
 * Download all documents concatenated into a single master bundle Markdown file.
 */
export function downloadCombinedMarkdown(
  documents: GeneratedDocument[],
  bundleFilename: string = "AI_CONTEXT_BUNDLE.md"
): void {
  if (!documents || documents.length === 0) return;

  const header = `# AI Context Engineering Bundle\n*Generated by AI Context Orchestrator*\n\n---\n\n## Table of Contents\n${documents
    .map((doc, idx) => `${idx + 1}. [${doc.filename}](#${doc.name.toLowerCase()})`)
    .join("\n")}\n\n---\n\n`;

  const content = documents
    .map(
      (doc) =>
        `<a id="${doc.name.toLowerCase()}"></a>\n\n# ${doc.filename}\n\n${doc.content}\n\n---\n`
    )
    .join("\n\n");

  const blob = new Blob([header + content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const anchor = window.document.createElement("a");
  anchor.href = url;
  anchor.download = bundleFilename;
  anchor.click();
  URL.revokeObjectURL(url);
}

/**
 * Convert a Markdown document to PDF and trigger download.
 * Uses html2pdf.js for client-side conversion.
 */
export async function downloadAsPdf(document: GeneratedDocument): Promise<void> {
  const html2pdf = (await import("html2pdf.js")).default;

  const container = window.document.createElement("div");
  container.innerHTML = await markdownToPdfHtml(document.content);
  container.style.padding = "32px 40px";
  container.style.fontFamily = "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";
  container.style.fontSize = "11px";
  container.style.lineHeight = "1.6";
  container.style.color = "#1a1a1a";
  container.style.backgroundColor = "#ffffff";

  const options = {
    margin: [12, 12, 12, 12] as [number, number, number, number],
    filename: document.filename.replace(".md", ".pdf"),
    image: { type: "jpeg" as const, quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, letterRendering: true },
    jsPDF: { unit: "mm", format: "a4", orientation: "portrait" as const },
    pagebreak: { mode: ["avoid-all", "css", "legacy"] },
  };

  await html2pdf().set(options as any).from(container).save();
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * Render Mermaid to SVG before html2canvas captures the PDF container.
 * Invalid diagrams remain visible as source instead of disappearing.
 */
export async function markdownToPdfHtml(markdown: string): Promise<string> {
  const diagrams: string[] = [];
  const normalized = normalizeMermaidMarkdown(markdown);
  const markdownWithTokens = normalized.replace(
    /```mermaid\s*\n([\s\S]*?)```/gi,
    (_match, source: string) => {
      const index = diagrams.push(source.trim()) - 1;
      return `\n\nMERMAID_DIAGRAM_${index}_PLACEHOLDER\n\n`;
    }
  );

  let html = markdownToSimpleHtml(markdownWithTokens);

  for (let index = 0; index < diagrams.length; index += 1) {
    const source = diagrams[index];
    let replacement: string;

    try {
      const svg = await renderMermaidSvg(
        `mermaid-pdf-${Date.now()}-${index}`,
        source
      );
      replacement = `<div style="margin:16px 0;padding:12px;border:1px solid #cbd5e1;border-radius:8px;background:#121619;page-break-inside:avoid;overflow:hidden;">${svg}</div>`;
    } catch {
      replacement = `<div style="margin:16px 0;page-break-inside:avoid;"><p style="color:#b45309;font-weight:600;">Diagram belum dapat ditampilkan. Kode Mermaid:</p><pre style="background:#f8fafc;border:1px solid #e2e8f0;padding:12px;font-family:monospace;font-size:10px;line-height:1.4;white-space:pre-wrap;word-break:break-word;"><code>${escapeHtml(source)}</code></pre></div>`;
    }

    html = html.replace(`MERMAID_DIAGRAM_${index}_PLACEHOLDER`, replacement);
  }

  return html;
}

/**
 * Robust Markdown to HTML converter for PDF generation.
 * Handles headers, tables, code blocks, blockquotes, lists, and formatting.
 */
export function markdownToSimpleHtml(markdown: string): string {
  if (!markdown) return "";

  // Escape raw HTML before applying the limited Markdown transformations.
  let html = markdown
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  // Code blocks (multi-line)
  html = html.replace(/```(?:[a-zA-Z0-9_-]+)?\n([\s\S]*?)```/g, (_match, code) => {
    return `<pre style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:6px;padding:12px;margin:12px 0;font-family:monospace;font-size:10px;line-height:1.4;white-space:pre-wrap;word-break:break-all;page-break-inside:avoid;"><code>${code}</code></pre>`;
  });

  // Tables
  html = html.replace(
    /(?:^\|[^\n]+\|\r?\n)((?:\|[^\n]+\|\r?\n?)+)/gm,
    (tableMatch) => {
      const rows = tableMatch.trim().split("\n");
      if (rows.length < 2) return tableMatch;

      let tableHtml = `<table style="width:100%;border-collapse:collapse;margin:14px 0;font-size:10.5px;page-break-inside:avoid;">`;
      rows.forEach((row, idx) => {
        const cells = row
          .split("|")
          .map((c) => c.trim())
          .filter((_, cIdx, arr) => cIdx > 0 && cIdx < arr.length - 1);

        // Skip separator row (e.g. |---|---|)
        if (cells.every((c) => /^:?-+:?$/.test(c))) return;

        const isHeader = idx === 0;
        const tag = isHeader ? "th" : "td";
        const bgStyle = isHeader
          ? "background:#f1f5f9;font-weight:600;text-align:left;border:1px solid #cbd5e1;padding:6px 10px;"
          : "border:1px solid #e2e8f0;padding:6px 10px;";

        tableHtml += "<tr>";
        cells.forEach((cell) => {
          tableHtml += `<${tag} style="${bgStyle}">${cell}</${tag}>`;
        });
        tableHtml += "</tr>";
      });
      tableHtml += "</table>";
      return tableHtml;
    }
  );

  // Blockquotes
  html = html.replace(/^>\s*(.*$)/gm, "<blockquote style='border-left:3px solid #4338ca;margin:10px 0;padding:6px 12px;color:#475569;background:#f8fafc;font-style:italic;'>$1</blockquote>");

  // Headings with page-break avoidance
  html = html
    .replace(/^#### (.*$)/gm, "<h4 style='font-size:12px;font-weight:600;color:#1e293b;margin:14px 0 6px;page-break-after:avoid;'>$1</h4>")
    .replace(/^### (.*$)/gm, "<h3 style='font-size:13.5px;font-weight:600;color:#1e293b;margin:16px 0 6px;page-break-after:avoid;'>$1</h3>")
    .replace(/^## (.*$)/gm, "<h2 style='font-size:15px;font-weight:700;color:#0f172a;margin:20px 0 8px;border-bottom:1px solid #e2e8f0;padding-bottom:4px;page-break-after:avoid;'>$1</h2>")
    .replace(/^# (.*$)/gm, "<h1 style='font-size:18px;font-weight:800;color:#0f172a;margin:24px 0 10px;border-bottom:2px solid #cbd5e1;padding-bottom:6px;page-break-after:avoid;'>$1</h1>");

  // Inline formatting
  html = html
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code style='background:#f1f5f9;padding:1px 4px;border-radius:3px;font-size:10px;font-family:monospace;'>$1</code>")
    .replace(/^- (.*$)/gm, "<li style='margin-left:18px;margin-bottom:3px;'>$1</li>")
    .replace(/^\* (.*$)/gm, "<li style='margin-left:18px;margin-bottom:3px;'>$1</li>")
    .replace(/^(\d+)\. (.*$)/gm, "<li style='margin-left:18px;margin-bottom:3px;'>$2</li>")
    .replace(/^---$/gm, "<hr style='border:none;border-top:1px solid #e2e8f0;margin:16px 0;'>")
    .replace(/\n\n/g, "</p><p style='margin:8px 0;'>")
    .replace(/\n/g, "<br>");

  return `<div style="max-width:720px;margin:0 auto;color:#1e293b;">${html}</div>`;
}
